# Generated by Django 6.0.7 on 2026-07-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='provider',
        ),
    ]
