# Generated by Django 6.0.7 on 2026-07-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_item_app_item_source_valid_alter_item_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_type',
            field=models.CharField(choices=[('official', 'Offical'), ('aired', 'Aired'), ('dvd', 'DVD'), ('absolute', 'Absolute'), ('alternate', 'Alternate'), ('alttwo', 'Alternate Variant'), ('regional', 'Regional'), ('digital', 'Digital')], default='official', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.CharField(choices=[('tmdb', 'The Movie Database')], default='tmdb', max_length=20),
        ),
    ]
