[supervisord]
nodaemon=true
user=root


[program:gunicorn]
directory=/app
command=gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[program:celery_worker]
directory=/app
command=celery -A config worker --loglevel=INFO --without-mingle --without-gossip
autorestart=true
stopasgroup=true
stopwaitsecs=60
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[program:celery_beat]
directory=/app
command=celery -A config beat --scheduler django --loglevel=INFO
autorestart=true
stopasgroup=true
priority=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0