# Generated by Django 5.1.5 on 2025-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_anime_unique_together_and_more'),
        ('lists', '0002_alter_customlistitem_item_alter_customlist_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customlistitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customlistitem',
            constraint=models.UniqueConstraint(fields=('item', 'custom_list'), name='lists_customlistitem_unique_item_list'),
        ),
    ]
