# Generated by Django 5.1.7 on 2025-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0023_user_home_sort_user_home_sort_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='lists_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='lists_sort',
            field=models.CharField(choices=[('last_item_added', 'Last Item Added'), ('name', 'Name'), ('items_count', 'Items Count'), ('newest_first', 'Newest First')], default='last_item_added', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('lists_sort__in', ['last_item_added', 'name', 'items_count', 'newest_first'])), name='lists_sort_valid'),
        ),
    ]
