# Generated by Django 5.1.7 on 2025-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0026_user_anime_sort_user_book_sort_user_game_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_detail_sort',
            field=models.CharField(choices=[('date_added', 'Date Added'), ('title', 'Title'), ('media_type', 'Media Type')], default='date_added', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_sort__in', ['date_added', 'title', 'media_type'])), name='list_detail_sort_valid'),
        ),
    ]
