# Generated by Django 6.0.7 on 2026-07-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese')], default='en', max_length=10),
        ),
    ]
