# Generated by Django 6.0.7 on 2026-07-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('pt-PT', 'Portuguese (Portugal)')], default='en-US', max_length=10),
        ),
    ]
