# Generated by Django 6.0.7 on 2026-07-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watch_provider_region',
            new_name='watch_provider_region_tmdb',
        ),
        migrations.AddField(
            model_name='user',
            name='watch_provider_region_tvdb',
            field=models.CharField(default='UNSET', help_text='Region to show watch providers for', max_length=5),
        ),
    ]
