# Generated by Django 6.0.7 on 2026-07-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_rename_watch_provider_region_user_watch_provider_region_tmdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_anime_source',
            field=models.CharField(choices=[('mal', 'Mal')], default='mal', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_boardgame_source',
            field=models.CharField(choices=[('bgg', 'Bgg')], default='bgg', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_book_source',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('openlibrary', 'Openlibrary')], default='hardcover', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_comic_source',
            field=models.CharField(choices=[('comicvine', 'Comicvine')], default='comicvine', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_game_source',
            field=models.CharField(choices=[('igdb', 'Igdb')], default='igdb', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_manga_source',
            field=models.CharField(choices=[('mangaupdates', 'Mangaupdates')], default='mangaupdates', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_movie_source',
            field=models.CharField(choices=[('tmdb', 'Tmdb'), ('tvdb', 'Tvdb')], default='tmdb', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_tv_source',
            field=models.CharField(choices=[('tmdb', 'Tmdb'), ('tvdb', 'Tvdb')], default='tmdb', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='prefered_tvdb_air_order',
            field=models.CharField(choices=[('official', 'Offical'), ('aired', 'Aired'), ('dvd', 'DVD'), ('absolute', 'Absolute'), ('alternate', 'Alternate'), ('alttwo', 'Alternate Variant'), ('regional', 'Regional'), ('digital', 'Digital')], default='official', max_length=20),
        ),
    ]
