# Generated by Django 6.0.7 on 2026-07-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_user_default_anime_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_anime_source',
            field=models.CharField(choices=[('mal', 'MyAnimeList')], default='mal', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_boardgame_source',
            field=models.CharField(choices=[('bgg', 'BoardGameGeek')], default='bgg', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_book_source',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('openlibrary', 'Open Library')], default='hardcover', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_comic_source',
            field=models.CharField(choices=[('comicvine', 'Comic Vine')], default='comicvine', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_game_source',
            field=models.CharField(choices=[('igdb', 'Internet Game Database')], default='igdb', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_manga_source',
            field=models.CharField(choices=[('mangaupdates', 'MangaUpdates')], default='mangaupdates', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_movie_source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB')], default='tmdb', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_tv_source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB')], default='tmdb', max_length=20),
        ),
    ]
