# Generated by Django 6.0.7 on 2026-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_user_default_anime_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_provider_tmdb',
            field=models.CharField(choices=[('tmdb', 'The Movie Database')], default='tmdb', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_provider_tvdb',
            field=models.CharField(choices=[('tmdb', 'The Movie Database')], default='tmdb', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='watch_provider_region_tmdb',
            field=models.CharField(default='UNSET', help_text='Region to show watch providers for TMDB', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='watch_provider_region_tvdb',
            field=models.CharField(default='UNSET', help_text='Region to show watch providers for TVDB', max_length=5),
        ),
    ]
