# Generated by Django 6.0.7 on 2026-07-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_user_watch_provider_tmdb_user_watch_provider_tvdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_order_type',
            field=models.CharField(choices=[('official', 'Offical'), ('aired', 'Aired'), ('dvd', 'DVD'), ('absolute', 'Absolute'), ('alternate', 'Alternate'), ('alttwo', 'Alternate Variant'), ('regional', 'Regional'), ('digital', 'Digital')], default='official', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Boardgame')], default='tv', max_length=10),
        ),
    ]
