# Generated by Django 6.0.7 on 2026-07-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_user_last_order_type_user_last_source_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefered_tvdb_air_order',
            new_name='prefered_air_order',
        ),
    ]
