# Generated by Django 6.0.7 on 2026-07-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_rename_prefered_tvdb_air_order_user_prefered_air_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_source_used',
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_anime',
            field=models.CharField(choices=[('mal', 'MyAnimeList')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_boardgame',
            field=models.CharField(choices=[('bgg', 'BoardGameGeek')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_book',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('openlibrary', 'Open Library')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_comic',
            field=models.CharField(choices=[('comicvine', 'Comic Vine')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_game',
            field=models.CharField(choices=[('igdb', 'Internet Game Database')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_manga',
            field=models.CharField(choices=[('mangaupdates', 'MangaUpdates')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_movie',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_source_used_tv',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Boardgame')], default='tv', max_length=20),
        ),
    ]
