# Generated by Django 6.0.7 on 2026-07-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_user_last_source_used_anime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_source_used_anime',
            field=models.CharField(choices=[('mal', 'MyAnimeList')], default='mal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_boardgame',
            field=models.CharField(choices=[('bgg', 'BoardGameGeek')], default='bgg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_book',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('openlibrary', 'Open Library')], default='hardcover', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_comic',
            field=models.CharField(choices=[('comicvine', 'Comic Vine')], default='comicvine', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_game',
            field=models.CharField(choices=[('igdb', 'Internet Game Database')], default='igdb', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_manga',
            field=models.CharField(choices=[('mangaupdates', 'MangaUpdates')], default='mangaupdates', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_movie',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB')], default='tmdb', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_source_used_tv',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB')], default='tmdb', max_length=20, null=True),
        ),
    ]
