# Generated by Django 6.0.7 on 2026-07-21 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_number', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
            options={
                'ordering': ['-datetime'],
                'constraints': [models.UniqueConstraint(fields=('item', 'content_number'), name='unique_item_content_number'), models.UniqueConstraint(condition=models.Q(('content_number__isnull', True)), fields=('item',), name='unique_item_null_content_number')],
            },
        ),
    ]
