# Generated by Django 5.1.7 on 2025-03-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['datetime']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='datetime',
        ),
    ]
