# Generated by Django 5.1.7 on 2025-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_rename_date_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
