# Generated by Django 5.1.7 on 2025-04-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_tv_events'),
    ]

    operations = [
    ]
