# Generated by Django 5.1.7 on 2025-04-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_fix_movie_episode_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-datetime']},
        ),
    ]
