# Generated by Django 5.2 on 2025-04-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_comic_historicalcomic_and_more'),
        ('events', '0011_remove_event_unique_item_episode_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_item_episode',
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_item_null_episode',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('item', 'content_number'), name='unique_item_content_number'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('content_number__isnull', True)), fields=('item',), name='unique_item_null_content_number'),
        ),
    ]
